#!/usr/bin/env python3
"""
AI Log Analyzer - Main Entry Point

Standalone log analyzer module with LLM API.
Reads context from data/*.md (generated by generate_context.py).

Usage:
    python analyzer.py --mode manual --num-chunks 5
    python analyzer.py --mode manual --max-tokens 150000 --num-chunks 5
    python analyzer.py --mode auto --interval 3
"""

import os
import sys
import argparse
import time
from pathlib import Path
from typing import Optional

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

# Set UTF-8 encoding for output
import io
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

import yaml
from dotenv import load_dotenv

from src.orchestrator import LogAnalyzer
from src.llm import GLMClient


def load_config(config_file: str = "config.yaml") -> dict:
    """Load configuration from YAML file."""
    config_path = Path(config_file)
    if not config_path.exists():
        print(f"Config file not found: {config_path}")
        print(f"Copy config.example.yaml to config.yaml and customize")
        sys.exit(1)

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"Failed to load config: {e}")
        sys.exit(1)


def load_env():
    """Load environment variables from .env file."""
    env_file = Path(__file__).parent / ".env"
    if env_file.exists():
        load_dotenv(env_file)
    else:
        print(".env file not found, falling back to environment variables")

    if not os.getenv("GLM_API_KEY"):
        print("GLM_API_KEY not set. Add it to .env or export it in your shell.")
        sys.exit(1)


def run_manual_analysis(
    config: dict,
    num_chunks: Optional[int] = None,
    max_tokens: Optional[int] = None
) -> dict:
    """Run single analysis (manual mode)."""
    log_file = config['project']['log_file']
    api_config = config['api']
    analysis_config = config['analysis']
    storage_config = config['storage']

    glm_api_key = os.getenv("GLM_API_KEY")
    glm_base_url = os.getenv("GLM_BASE_URL", "https://api.z.ai/api/paas/v4/")

    # CLI overrides
    if num_chunks is not None:
        analysis_config['num_chunks'] = num_chunks
    if max_tokens is not None:
        analysis_config['max_total_tokens'] = max_tokens

    # Create LLM client
    pricing = api_config.get('pricing', {})
    llm_client = GLMClient(
        api_key=glm_api_key,
        base_url=glm_base_url,
        model=api_config['model'],
        max_output_tokens=api_config.get('max_output_tokens', 4000),
        temperature=api_config.get('temperature', 0.3),
        price_per_1k_input=pricing.get('input_per_1k', 0.001),
        price_per_1k_output=pricing.get('output_per_1k', 0.002)
    )

    analyzer = LogAnalyzer(
        log_file=log_file,
        llm_client=llm_client,
        state_file=storage_config['state_file'],
        reports_dir=storage_config['reports_dir'],
        data_dir=storage_config.get('data_dir', './data'),
        num_chunks=analysis_config.get('num_chunks', 5),
        chunk_size_lines=analysis_config.get('chunk_size_lines', 2000),
        max_total_tokens=analysis_config.get('max_total_tokens', 0),
        max_chunk_tokens=analysis_config.get('max_chunk_tokens', 0),
        retention_days=config.get('project', {}).get('retention_days', 7),
        max_cost_usd=analysis_config['max_cost_usd'],
        combine_prompt=analysis_config.get('combine_prompt', 'create_report_with_anomalies'),
        prompts_language=api_config.get('prompts_language', 'ru')
    )

    return analyzer.analyze()


def run_auto_mode(config: dict):
    """Run in automatic mode (scheduler)."""
    interval_hours = config['mode']['check_interval_hours']
    print(f"Starting automatic mode (interval: {interval_hours}h)")
    print(f"Press Ctrl+C to stop\n")

    try:
        while True:
            print(f"\n[{time.strftime('%Y-%m-%d %H:%M:%S')}] Starting scheduled analysis...")
            try:
                run_manual_analysis(config)
            except Exception as e:
                print(f"Analysis failed: {e}")
                import traceback
                traceback.print_exc()

            sleep_seconds = interval_hours * 3600
            print(f"\nSleeping for {interval_hours}h until next check...")
            time.sleep(sleep_seconds)
    except KeyboardInterrupt:
        print(f"\n\nStopped by user")
        sys.exit(0)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="AI Log Analyzer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Manual analysis with default settings
  python analyzer.py --mode manual

  # Specify number of chunks
  python analyzer.py --mode manual --num-chunks 3

  # Token-based chunking (150K tokens split into 5 chunks)
  python analyzer.py --mode manual --max-tokens 150000 --num-chunks 5

  # Automatic mode (scheduler)
  python analyzer.py --mode auto

  # Use custom config file
  python analyzer.py --config my_config.yaml --mode manual
        """
    )

    parser.add_argument(
        "--mode", choices=["manual", "auto"], default="manual",
        help="Run mode: manual (single analysis) or auto (scheduler)"
    )
    parser.add_argument(
        "--config", default="config.yaml",
        help="Path to config file (default: config.yaml)"
    )
    parser.add_argument(
        "--num-chunks", type=int,
        help="Number of log chunks to analyze (default: from config)"
    )
    parser.add_argument(
        "--max-tokens", type=int,
        help="Total token budget for all chunks (e.g., 150000). Overrides chunk_size_lines."
    )
    parser.add_argument(
        "--interval", type=int,
        help="Override check_interval_hours from config (auto mode only)"
    )

    args = parser.parse_args()
    load_env()
    config = load_config(args.config)

    if args.interval:
        config['mode']['check_interval_hours'] = args.interval

    if args.mode == "manual":
        report = run_manual_analysis(
            config,
            num_chunks=args.num_chunks,
            max_tokens=args.max_tokens
        )
        print(f"\nAnalysis Summary:")
        print(f"  Status: {report['system_status']}")
        print(f"  Shutdown: {'Yes' if report['should_shutdown'] else 'No'}")
        print(f"  Issues: {len(report['issues'])}")
        print(f"  Cost: ${report['statistics']['cost_usd']:.4f}")
    elif args.mode == "auto":
        run_auto_mode(config)


if __name__ == "__main__":
    main()
